services:
  web_server:
    build: .
    ports:
      - "5000"
    depends_on:
      - redis_server
    volumes:
      - .:/my_code


  redis_server:
    image: redis:latest
    container_name: redis_server   
    ports:
      - "6379:6379"


  nginx_lb:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx_lb
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_server
